#%RAML 0.8
title: Exercise API KIT
version: 01

schemas:
  - book: |
      {
        "properties": {
          "ID": {
            "description": "Book ID",
            "type": "number",
            "required": true
          },
          "title": {
            "description": "book's title",
            "type": "string",
            "required": true
          },
          "author": {
            "description": "book's uthor",
            "type": "string",
            "required": true
          },
          "origin": {
            "pages": "number pages",
            "type": "number",
            "required": true
          }
        }
      }
  - books: |
      [{
        "properties": {
          "ID": {
            "description": "Book ID",
            "type": "number",
            "required": true
          },
          "title": {
            "description": "book's title",
            "type": "string",
            "required": true
          },
          "author": {
            "description": "book's uthor",
            "type": "string",
            "required": true
          },
          "origin": {
            "pages": "number pages",
            "type": "number",
            "required": true
          }
        }
      }]
    
    
/books:
  description: methods for management books
  get:
    description: Retrieve all books
    headers: 
      User-Agent: 
        required: true
    responses:
      200:
        body:
          application/json:
            example: |
              [{"ID":1, "title": "book1","author": "author1", "pages": 12},{"ID":2, "title": "book2","author": "author2", "pages": 45},{"ID":1, "title": "book3","author": "author3", "pages": 25}]
  put:
    description: Create a new book
    headers: 
      User-Agent: 
        required: true
    body:
      application/json:  
        example: |
          {"title": "book1","author": "author1", "pages": 12}

    responses:
      201:
        body:
          application/json:
            example: |
              {"message": "book created with id: 5"}

  post:
    description: Update a new book
    headers: 
      User-Agent: 
        required: true
    body:
      application/json:
        schema: book 
        example: |
          {"ID":3, "title": "book55","author": "author77", "pages": 33}

    responses:
      201:
        body:
          application/json:
            example: |
              {"message": "Book updated"}
              
  /{NAME}:
    description: methods for books management and that required parameter "name"
    get:
      description: Search a specific book by name
      headers: 
        User-Agent: 
          required: true
      responses:
        200:
          body:
            application/json:
              schema: book
              example: |
                {"ID":2, "title": "book2","author": "author2", "pages": 45}
  
  /{ID}:
    description: methods for books management and that required parameter "ID"
    delete:
      description: Delete a book by ID
      headers: 
        User-Agent: 
          required: true    
      responses:
        200:
          body:
            application/json:
              example: |
                {"message": "Book deleted"} 